### ISSUE TITLE
thread

### ISSUE THREAD

**Issue by raffyOmega** [ed-archer/animepahe-dlr#21]
can you put some option like threads to make the download faster in normal mode(not idm) 

thank you.

**Comment by ajxv** [comment]
Hi @raffyOmega. 

I'll look into the possible ways to speed up the downloads. Can't promise anything though, since its outside my area of expertise at the moment.

Also, note that download speed is affected by both your network speed and also the speed throttling on the server side (I personally get around 8mbps at times and as lower as 60kbps at other times for the episodes of the same series depending on the time of day). That is to say even if threading is introduced it may not improve the download speed.
